Tank Controller Lib: MainMenu Class Reference
MainMenu Class Reference
#include <MainMenu.h>
Public Member Functions
MainMenu (TankControllerLib *tc)
virtual void handleKey (char key)
const char * prompt ()
virtual bool isMainMenu ()
Public Member Functions inherited from UIState
UIState (TankControllerLib *tc)
virtual ~UIState ()
virtual void start ()
Additional Inherited Members
Static Public Member Functions inherited from UIState
static bool addSleepHandler (SleepHandler pFunction)
static bool removeSleepHandler (SleepHandler pFunction)
static void sleep (int ms)
Protected Member Functions inherited from UIState
void setNextState (UIState *state)
void returnToMainMenu (int msDelay=0)
Protected Attributes inherited from UIState
TankControllerLib * tc = nullptr
Detailed Description
Definition at line 12 of file MainMenu.h.
Constructor & Destructor Documentation
MainMenu()
MainMenu::MainMenu (TankControllerLib * tc) inline
Definition at line 14 of file MainMenu.h.
                                   : UIState(tc) {
   }
Member Function Documentation
handleKey()
void MainMenu::handleKey (char key) virtual
Branch to other states to handle various menu options
Reimplemented from UIState.
Definition at line 23 of file MainMenu.cpp.
{
   switch (key) {
     case 'A':  // Set pH set_point
       this->setNextState((UIState*)new SetPHSetPoint(tc));
       break;
     case 'B':  // Set Temperature set_point
       this->setNextState((UIState*)new SetTempSetPoint(tc));
       break;
     case 'C':  // pH Calibration
       this->setNextState((UIState*)new PHCalibration(tc));
       break;
     case 'D':  // Calibration Management
       this->setNextState((UIState*)new CalibrationManagement(tc));
       break;
     case '#':  // Set Tank ID
       this->setNextState((UIState*)new SetTankID(tc));
       break;
     case '*':  // Set Google Sheet Interval
       this->setNextState((UIState*)new SetGoogleSheetInterval(tc));
       break;
     case '0':  // See Device Uptime & Current Time
       this->setNextState((UIState*)new SeeDeviceUptime(tc));
       break;
     case '1':  // See Device addresses
       this->setNextState((UIState*)new SeeDeviceAddress(tc));
       break;
     case '2':  // Reset LCD Screen
       this->setNextState((UIState*)new ResetLCDScreen(tc));
       break;
     case '3':  // See Tank ID and Log File Name
       this->setNextState((UIState*)new SeeTankID(tc));
       break;
     case '4':  // See PID Constants
       this->setNextState((UIState*)new SeePIDConstants(tc));
       break;
     case '5':  // PID Tuning
       this->setNextState((UIState*)new PIDTuningMenu(tc));
       break;
     case '6':  // Temperature Calibration
       this->setNextState((UIState*)new TemperatureCalibration(tc));
       break;
     case '7':  // Manual Set Time
       this->setNextState((UIState*)new SetTime(tc));
       break;
     case '8':  // Enable PID
       this->setNextState((UIState*)new EnablePID(tc));
       break;
     case '9':  // Set Chill or Heat
       this->setNextState((UIState*)new SetChillOrHeat(tc));
       break;
     default:
       returnToMainMenu();
       break;
   }
 }
References key(), UIState::returnToMainMenu(), UIState::setNextState(), and UIState::tc.
Referenced by TankController.TankController::Keyboard(), and TankController.TankController::KeypadEvent().
isMainMenu()
virtual bool MainMenu::isMainMenu () inline virtual
Reimplemented from UIState.
Definition at line 20 of file MainMenu.h.
{
     return true;
   }
prompt()
const char* MainMenu::prompt () inline virtual
Reimplemented from UIState.
Definition at line 17 of file MainMenu.h.
{
     return "Main Menu       ";
   };
The documentation for this class was generated from the following files:
src/UIState/MainMenu.h
src/UIState/MainMenu.cpp