Tank Controller Lib: UIState Class Reference
UIState Class Reference
#include <UIState.h>
Public Member Functions
UIState (TankControllerLib *tc)
virtual ~UIState ()
virtual void handleKey (char key)
virtual bool isMainMenu ()
virtual const char * prompt ()
virtual void start ()
Static Public Member Functions
static bool addSleepHandler (SleepHandler pFunction)
static bool removeSleepHandler (SleepHandler pFunction)
static void sleep (int ms)
Protected Member Functions
void setNextState (UIState *state)
void returnToMainMenu (int msDelay=0)
Protected Attributes
TankControllerLib * tc = nullptr
Static Private Attributes
static const int SLEEP_HANDLERS_COUNT = 5
static SleepHandler sleepHandlers [SLEEP_HANDLERS_COUNT]
Detailed Description
Definition at line 13 of file UIState.h.
Constructor & Destructor Documentation
UIState()
UIState::UIState (TankControllerLib * tc) inline
Definition at line 16 of file UIState.h.
{
     this->tc = tc;
   }
References tc.
~UIState()
virtual UIState::~UIState () inline virtual
Definition at line 20 of file UIState.h.
                      {
   }
Member Function Documentation
addSleepHandler()
bool UIState::addSleepHandler (SleepHandler pFunction) static
Definition at line 27 of file UIState.cpp.
{
   for (int i = 0; i < SLEEP_HANDLERS_COUNT; ++i) {
     if (!sleepHandlers[i]) {
       sleepHandlers[i] = pFunction;
       return true;
     }
   }
   return false;
 }
References SLEEP_HANDLERS_COUNT, and sleepHandlers.
Referenced by unittest().
handleKey()
void UIState::handleKey (char key) virtual
Reimplemented in TemperatureCalibration, SeeTankID, SeePIDConstants, SeeDeviceAddress, ResetLCDScreen, PIDTuningMenu, PHCalibration, NumCollectorState, MainMenu, EnablePID, and CalibrationManagement.
Definition at line 59 of file UIState.cpp.
{
   // default is to just return to main menu
   // this is useful for display-only actions
   this->returnToMainMenu();
 }
References returnToMainMenu().
Referenced by TankControllerLib::handleUI(), TankController.TankController::Keyboard(), and TankController.TankController::KeypadEvent().
isMainMenu()
virtual bool UIState::isMainMenu () inline virtual
Reimplemented in MainMenu.
Definition at line 29 of file UIState.h.
{
     return false;
   }
prompt()
virtual const char* UIState::prompt () inline virtual
Reimplemented in TemperatureCalibration, SetTime, SetTempSetPoint, SetTankID, SetPHSetPoint, SetGoogleSheetInterval, SetChillOrHeat, SeeTankID, SeePIDConstants, SeeDeviceAddress, ResetLCDScreen, PIDTuningMenu, PHCalibration, MainMenu, EnablePID, and CalibrationManagement.
Definition at line 32 of file UIState.h.
{
     return "                ";
   }
Referenced by start().
removeSleepHandler()
bool UIState::removeSleepHandler (SleepHandler pFunction) static
Definition at line 37 of file UIState.cpp.
{
   for (int i = 0; i < SLEEP_HANDLERS_COUNT; ++i) {
     if (sleepHandlers[i] == pFunction) {
       sleepHandlers[i] = nullptr;
       return true;
     }
   }
   return false;
 }
References SLEEP_HANDLERS_COUNT, and sleepHandlers.
Referenced by unittest().
returnToMainMenu()
void UIState::returnToMainMenu (int msDelay = 0) protected
Definition at line 65 of file UIState.cpp.
{
   if (msDelay) {
     sleep(msDelay);
   }
   this->setNextState((UIState*)new MainMenu(tc));
 }
References setNextState(), sleep(), and tc.
Referenced by CalibrationManagement::handleKey(), EnablePID::handleKey(), MainMenu::handleKey(), NumCollectorState::handleKey(), PHCalibration::handleKey(), PIDTuningMenu::handleKey(), ResetLCDScreen::handleKey(), SeeDeviceAddress::handleKey(), SeePIDConstants::handleKey(), SeeTankID::handleKey(), TemperatureCalibration::handleKey(), handleKey(), SetChillOrHeat::setValue(), SetGoogleSheetInterval::setValue(), SetPHSetPoint::setValue(), SetTankID::setValue(), SetTempSetPoint::setValue(), SetTime::setValue(), and SeeDeviceUptime::start().
setNextState()
void UIState::setNextState (UIState * state) protected
Definition at line 72 of file UIState.cpp.
{
   tc->setNextState(state);
 }
References TankControllerLib::setNextState(), state, and tc.
Referenced by MainMenu::handleKey(), and returnToMainMenu().
sleep()
void UIState::sleep (int ms) static
Definition at line 47 of file UIState.cpp.
{
   for (int i = 0; i < SLEEP_HANDLERS_COUNT; ++i) {
     SleepHandler pFunction = sleepHandlers[i];
     if (pFunction) {
       pFunction(ms);
     }
   }
   delay(ms);
 }
References SLEEP_HANDLERS_COUNT, and sleepHandlers.
Referenced by returnToMainMenu(), and unittest().
start()
void UIState::start () virtual
Reimplemented in SeeDeviceUptime.
Definition at line 76 of file UIState.cpp.
                     {
   // default is to print the current prompt on the first line of the display
   const char* prompt = this->prompt();
   LiquidCrystal_TC::instance()->writeLine(prompt, 0);
   LiquidCrystal_TC::instance()->writeLine("                ", 1);
 }
References LiquidCrystal_TC::instance(), prompt(), and LiquidCrystal_TC::writeLine().
Referenced by SetTime::setValue(), and TankControllerLib::updateState().
Member Data Documentation
SLEEP_HANDLERS_COUNT
const int UIState::SLEEP_HANDLERS_COUNT = 5 static private
Definition at line 43 of file UIState.h.
Referenced by addSleepHandler(), removeSleepHandler(), and sleep().
sleepHandlers
SleepHandler UIState::sleepHandlers static private
SleepHandler
When running on the real Arduino, the delay() function will actually pause. When running on the mock Arduino, the delay() function increments the clock and then returns immediately. While this generally the right thing to do, this presents a couple issues. First, if we want to look at the state during the delay, this is difficult since the state could change after the delay (e.g., show a message on the LCD for one second, then clear it). Second, if we are using the mock Arduino library to emulate the application in a GUI, we want to have a real delay. To solve this, we will allow code (such as tests and the GUI) to register to be notified of delays. Then we can take whatever action is appropriate.
typedef void (*SleepHandler)(int ms);
Definition at line 44 of file UIState.h.
Referenced by addSleepHandler(), removeSleepHandler(), and sleep().
tc
TankControllerLib* UIState::tc = nullptr protected
Definition at line 40 of file UIState.h.
Referenced by MainMenu::handleKey(), returnToMainMenu(), setNextState(), and UIState().
The documentation for this class was generated from the following files:
src/UIState/UIState.h
src/UIState/UIState.cpp