Tank Controller Lib: Serial_TC Class Reference
Serial_TC Class Reference
#include <Serial_TC.h>
Public Member Functions
void print (char aChar) const
void print (uint16_t anInt) const
void print (double aDouble, int scale=2) const
void print (const String aString, bool newLine=true) const
void print (const String aString, char aChar) const
void print (const String aString, int anInt) const
void print (const String aString, int anInt, int format) const
void print (const char *aString, const char *aString2) const
void print (const String aString, const String aString2) const
void println () const
void print_mac (const byte mac[]) const
void print_two_digits (int value) const
void write (byte aByte) const
void write (const char arr[], int anInt) const
Static Public Member Functions
static Serial_TC * instance ()
Private Member Functions
Serial_TC ()
Static Private Attributes
static Serial_TC * _instance = nullptr
Detailed Description
This class is for the Serial Commands used in Tank Controller. Serial here mostly deals with writing or printing data over through the serial port. Serial.print and Serial.write can be called in different ways to print data. Also print_PID, print_DataTime, print_mac are used to print the PID information, current date information, and the mac address.
Definition at line 12 of file Serial_TC.h.
Constructor & Destructor Documentation
Serial_TC()
Serial_TC::Serial_TC () private
constructor (private so clients use the singleton)
Definition at line 24 of file Serial_TC.cpp.
                      {
   Serial.begin(9600);
 }
Referenced by instance().
Member Function Documentation
instance()
Serial_TC * Serial_TC::instance () static
static member function to return singleton
Definition at line 13 of file Serial_TC.cpp.
{
   if (!_instance) {
     _instance = new Serial_TC();
   }
   return _instance;
 }
References _instance, and Serial_TC().
Referenced by PID_TC::logToSerial(), DateTime_TC::printToSerial(), SetTime::setValue(), TankControllerLib::TankControllerLib(), and unittest().
print() [1/9]
void Serial_TC::print (char aChar) const
Definition at line 28 of file Serial_TC.cpp.
{
   Serial.print(aChar);
 }
Referenced by TankControllerLib::handleUI(), DateTime_TC::printToSerial(), TankControllerLib::setup(), SetTime::setValue(), TankControllerLib::TankControllerLib(), unittest(), and TankControllerLib::version().
print() [2/9]
void Serial_TC::print (const char * aString, const char * aString2) const
Definition at line 63 of file Serial_TC.cpp.
{
   Serial.print(aString);
   Serial.println(aString2);
 }
print() [3/9]
void Serial_TC::print (const String aString, bool newLine = true) const
Definition at line 40 of file Serial_TC.cpp.
{
   if (newLine) {
     Serial.println(aString);
   } else {
     Serial.print(aString);
   }
 }
print() [4/9]
void Serial_TC::print (const String aString, char aChar) const
Definition at line 48 of file Serial_TC.cpp.
{
   Serial.print(aString);
   Serial.println(aChar);
 }
print() [5/9]
void Serial_TC::print (const String aString, const String aString2) const
Definition at line 68 of file Serial_TC.cpp.
{
   Serial.print(aString);
   Serial.println(aString2);
 }
print() [6/9]
void Serial_TC::print (const String aString, int anInt) const
Definition at line 53 of file Serial_TC.cpp.
{
   Serial.print(aString);
   Serial.println(anInt);
 }
print() [7/9]
void Serial_TC::print (const String aString, int anInt, int format) const
Definition at line 58 of file Serial_TC.cpp.
{
   Serial.print(aString);
   Serial.println(anInt, format);
 }
print() [8/9]
void Serial_TC::print (double aDouble, int scale = 2) const
Definition at line 36 of file Serial_TC.cpp.
{
   Serial.print(aDouble, scale);
 }
print() [9/9]
void Serial_TC::print (uint16_t anInt) const
Definition at line 32 of file Serial_TC.cpp.
{
   Serial.print(anInt);
 }
print_mac()
void Serial_TC::print_mac (const byte mac[]) const
Definition at line 73 of file Serial_TC.cpp.
{
   Serial.print(F("MAC Address: "));
   Serial.print(mac[0]);
   for (int i = 1; i < 6; ++i) {
     Serial.print(':');
     Serial.print(mac[i]);
   }
   Serial.println();
 }
Referenced by unittest().
print_two_digits()
void Serial_TC::print_two_digits (int value) const
function to add a leading zero digit
Definition at line 86 of file Serial_TC.cpp.
{
   if (value < 10) {
     Serial.print('0');
   }
   Serial.print(value, DEC);
 }
References value.
Referenced by unittest().
println()
void Serial_TC::println () const inline
Definition at line 27 of file Serial_TC.h.
{
     Serial.println();
   }
Referenced by unittest().
write() [1/2]
void Serial_TC::write (byte aByte) const
Definition at line 93 of file Serial_TC.cpp.
{
   Serial.write(aByte);
 }
Referenced by unittest().
write() [2/2]
void Serial_TC::write (const char arr[], int anInt) const
Definition at line 97 of file Serial_TC.cpp.
{
   Serial.write(arr, anInt);
 }
Member Data Documentation
_instance
Serial_TC * Serial_TC::_instance = nullptr static private
static variable for singleton
Definition at line 37 of file Serial_TC.h.
Referenced by instance().
The documentation for this class was generated from the following files:
src/Devices/Serial_TC.h
src/Devices/Serial_TC.cpp