Tank Controller Lib: ChangeGoogleSheetInterval Class Reference
ChangeGoogleSheetInterval Class Reference
#include <ChangeGoogleSheetInterval.h>
Public Member Functions
ChangeGoogleSheetInterval (TankControllerLib *tc)
void handleKey (char key)
const char * prompt ()
Public Member Functions inherited from UIState
UIState (TankControllerLib *tc)
virtual ~UIState ()
virtual bool isMainMenu ()
Additional Inherited Members
Protected Member Functions inherited from UIState
void setNextState (UIState *state)
void returnToMainMenu ()
Protected Attributes inherited from UIState
TankControllerLib * tc = nullptr
Detailed Description
ChangeGoogleSheetInterval.h
Change Google Sheet Interval
Definition at line 9 of file ChangeGoogleSheetInterval.h.
Constructor & Destructor Documentation
ChangeGoogleSheetInterval()
ChangeGoogleSheetInterval::ChangeGoogleSheetInterval (TankControllerLib * tc) inline
Definition at line 11 of file ChangeGoogleSheetInterval.h.
                                                    : UIState(tc) {
   }
Member Function Documentation
handleKey()
void ChangeGoogleSheetInterval::handleKey (char key) virtual
ChangeGoogleSheetInterval.cpp
Implements UIState.
Definition at line 7 of file ChangeGoogleSheetInterval.cpp.
{
   switch (key) {
     case 'D':  // Don't save (cancel)
       returnToMainMenu();
       break;
     default:
       break;
   };
 }
References key(), and UIState::returnToMainMenu().
Referenced by TankController.TankController::Keyboard(), and TankController.TankController::KeypadEvent().
prompt()
const char* ChangeGoogleSheetInterval::prompt () inline virtual
Implements UIState.
Definition at line 14 of file ChangeGoogleSheetInterval.h.
{
     return "G Sheet Interval";
   };
The documentation for this class was generated from the following files:
src/UIState/ChangeGoogleSheetInterval.h
src/UIState/ChangeGoogleSheetInterval.cpp