Tank Controller Lib: TankControllerLib Class Reference
TankControllerLib Class Reference
#include <TankControllerLib.h>
Public Member Functions
void setup ()
void loop ()
const char * version ()
virtual void setNextState (UIState *newState)
Static Public Member Functions
static TankControllerLib * instance ()
Protected Member Functions
TankControllerLib ()
~TankControllerLib ()
void blink ()
void updateState ()
void handleUI ()
Protected Attributes
UIState * state = nullptr
UIState * nextState = nullptr
LiquidCrystal_TC * lcd
Serial_TC * log
Static Protected Attributes
static TankControllerLib * _instance = nullptr
Detailed Description
Definition at line 17 of file TankControllerLib.h.
Constructor & Destructor Documentation
TankControllerLib()
TankControllerLib::TankControllerLib () protected
Constructor
Definition at line 28 of file TankControllerLib.cpp.
{
   assert(!_instance);
   state = new MainMenu(this);
   lcd = LiquidCrystal_TC::instance();
   log = Serial_TC::instance();
   log->print(F("TankControllerLib::TankControllerLib() - version "), TANK_CONTROLLER_VERSION);
   SDClass_TC::instance()->printRootDirectory();
 }
References _instance, assert, LiquidCrystal_TC::instance(), SDClass_TC::instance(), Serial_TC::instance(), lcd, log, Serial_TC::print(), SDClass_TC::printRootDirectory(), state, and TANK_CONTROLLER_VERSION.
Referenced by instance().
~TankControllerLib()
TankControllerLib::~TankControllerLib () protected
Destructor
Definition at line 40 of file TankControllerLib.cpp.
{
   delete state;
   delete nextState;
 }
References nextState, and state.
Member Function Documentation
blink()
void TankControllerLib::blink () protected
Blink the on-board LED to let us know that loop() is being called
Definition at line 49 of file TankControllerLib.cpp.
{
   if (millis() / 500 % 2) {
     digitalWrite(LED_BUILTIN, LOW);  // turn the LED off by making the voltage LOW
   } else {
     digitalWrite(LED_BUILTIN, HIGH);  // turn the LED on (HIGH is the voltage level)
   }
 }
Referenced by loop().
handleUI()
void TankControllerLib::handleUI () protected
Private member function called by loop Handles keypresses
Definition at line 77 of file TankControllerLib.cpp.
{
   char key = Keypad_TC::instance()->getKey();
   if (key != NO_KEY) {
     log->print(F("Keypad input: "), key);
     state->handleKey(key);
     updateState();
   }
 }
References Keypad_TC::getKey(), UIState::handleKey(), Keypad_TC::instance(), key(), log, Serial_TC::print(), state, and updateState().
Referenced by loop().
instance()
TankControllerLib * TankControllerLib::instance () static
static function to return singleton
Definition at line 17 of file TankControllerLib.cpp.
{
   if (!_instance) {
     _instance = new TankControllerLib;
   }
   return _instance;
 }
References _instance, and TankControllerLib().
Referenced by loop(), setup(), unittest(), and version().
loop()
void TankControllerLib::loop ()
This is one of two public instance functions. It is called repeatedly while the board is on.
Definition at line 90 of file TankControllerLib.cpp.
{
   blink();  //  blink the on-board LED to show that we are running
   handleUI();
 }
References blink(), and handleUI().
Referenced by loop(), and unittest().
setNextState()
virtual void TankControllerLib::setNextState (UIState * newState) inline virtual
Definition at line 26 of file TankControllerLib.h.
{
     assert(nextState == nullptr);
     nextState = newState;
   }
References assert, and nextState.
Referenced by UIState::setNextState(), and setup().
setup()
void TankControllerLib::setup ()
This is one of two public instance functions. Here we do any one-time startup initialization.
Definition at line 99 of file TankControllerLib.cpp.
{
   log->print(F("TankControllerLib::setup()"));
   setNextState(((UIState*)new MainMenu(this)));
   updateState();
   pinMode(LED_BUILTIN, OUTPUT);
 }
References log, Serial_TC::print(), setNextState(), and updateState().
Referenced by setup(), and unittest().
updateState()
void TankControllerLib::updateState () protected
Private member function called by UIState subclasses Only updates if a new state is available to switch to
Definition at line 61 of file TankControllerLib.cpp.
{
   if (nextState) {
     if (state) {
       delete state;
     }
     state = nextState;
     nextState = nullptr;
     // print the current prompt on the first line of the display
     LiquidCrystal_TC::instance()->writeLine(state->prompt(), 0);
   }
 }
References LiquidCrystal_TC::instance(), nextState, UIState::prompt(), state, and LiquidCrystal_TC::writeLine().
Referenced by handleUI(), and setup().
version()
const char * TankControllerLib::version ()
What is the current version?
Definition at line 109 of file TankControllerLib.cpp.
{
   log->print(F("TankControllerLib::version() = "), TANK_CONTROLLER_VERSION);
   return TANK_CONTROLLER_VERSION;
 }
References log, Serial_TC::print(), and TANK_CONTROLLER_VERSION.
Referenced by version().
Member Data Documentation
_instance
TankControllerLib * TankControllerLib::_instance = nullptr static protected
static variable to hold singleton
Definition at line 33 of file TankControllerLib.h.
Referenced by instance(), and TankControllerLib().
lcd
LiquidCrystal_TC* TankControllerLib::lcd protected
Definition at line 38 of file TankControllerLib.h.
Referenced by TankControllerLib().
log
Serial_TC* TankControllerLib::log protected
Definition at line 39 of file TankControllerLib.h.
Referenced by handleUI(), setup(), TankControllerLib(), and version().
nextState
UIState* TankControllerLib::nextState = nullptr protected
Definition at line 37 of file TankControllerLib.h.
Referenced by setNextState(), updateState(), and ~TankControllerLib().
state
UIState* TankControllerLib::state = nullptr protected
Definition at line 36 of file TankControllerLib.h.
Referenced by handleUI(), TankControllerLib(), updateState(), and ~TankControllerLib().
The documentation for this class was generated from the following files:
src/TankControllerLib.h
src/TankControllerLib.cpp