Tank Controller Lib: GUI/libTC.cpp File Reference
libTC.cpp File Reference
#include <limits>
#include <string>
#include <vector>
#include "Arduino.h"
#include "DateTime_TC.h"
#include "EEPROM_TC.h"
#include "Keypad_TC.h"
#include "LiquidCrystal_TC.h"
#include "Serial_TC.h"
#include "TankControllerLib.h"
#include "pybind11/pybind11.h"
Macros
#define NUM_SERIAL_PORTS 1
#define EEPROM_SIZE 4096
Functions
string dateTime ()
double eeprom (uint8_t index)
void key (char key)
const char * lcd (int index)
void loop ()
string serial ()
void setup ()
const char * version ()
PYBIND11_MODULE (libTC, m)
Variables
char lcdLine [20]
Macro Definition Documentation
EEPROM_SIZE
#define EEPROM_SIZE 4096
Definition at line 4 of file libTC.cpp.
NUM_SERIAL_PORTS
#define NUM_SERIAL_PORTS 1
Definition at line 3 of file libTC.cpp.
Function Documentation
dateTime()
string dateTime ()
Definition at line 22 of file libTC.cpp.
                   {
   DateTime_TC now = DateTime_TC::now();
   char buffer[20];
   strcpy(buffer, "YYYY-MM-DD hh:mm:ss");
   now.toString(buffer);
   return string(buffer);
 }
References DateTime_TC::now().
Referenced by PYBIND11_MODULE(), and unittest().
eeprom()
double eeprom (uint8_t index)
Definition at line 30 of file libTC.cpp.
{
   switch (index) {
     case 0:
       return EEPROM_TC::instance()->getPH();
     case 1:
       return EEPROM_TC::instance()->getTemp();
     case 2:
       return EEPROM_TC::instance()->getTankID();
     case 3:
       return EEPROM_TC::instance()->getCorrectedTemp();
     case 4:
       return EEPROM_TC::instance()->getKP();
     case 5:
       return EEPROM_TC::instance()->getKI();
     case 6:
       return EEPROM_TC::instance()->getKD();
     case 7:
       return EEPROM_TC::instance()->getMac();  // See issue #57 about this function
     case 8:
       return EEPROM_TC::instance()->getHeat();
     case 9:
       return EEPROM_TC::instance()->getAmplitude();
     case 10:
       return EEPROM_TC::instance()->getFrequency();
     case 11:
       return EEPROM_TC::instance()->getGranularity();
     case 12:
       return EEPROM_TC::instance()->getMaxDataAge();
     case 13:
       return EEPROM_TC::instance()->getPHSeriesSize();
     case 14:
       return EEPROM_TC::instance()->getPHSeriesPointer();
     case 15:
       return EEPROM_TC::instance()->getTempSeriesSize();
     case 16:
       return EEPROM_TC::instance()->getTempSeriesPointer();
     case 17:
       return EEPROM_TC::instance()->getPHInterval();
     case 18:
       return EEPROM_TC::instance()->getPHDelay();
     case 19:
       return EEPROM_TC::instance()->getTempInterval();
     case 20:
       return EEPROM_TC::instance()->getTempDelay();
     default:
       return std::numeric_limits<double>::quiet_NaN();
   }
 }
References EEPROM_TC::getAmplitude(), EEPROM_TC::getCorrectedTemp(), EEPROM_TC::getFrequency(), EEPROM_TC::getGranularity(), EEPROM_TC::getHeat(), EEPROM_TC::getKD(), EEPROM_TC::getKI(), EEPROM_TC::getKP(), EEPROM_TC::getMac(), EEPROM_TC::getMaxDataAge(), EEPROM_TC::getPH(), EEPROM_TC::getPHDelay(), EEPROM_TC::getPHInterval(), EEPROM_TC::getPHSeriesPointer(), EEPROM_TC::getPHSeriesSize(), EEPROM_TC::getTankID(), EEPROM_TC::getTemp(), EEPROM_TC::getTempDelay(), EEPROM_TC::getTempInterval(), EEPROM_TC::getTempSeriesPointer(), EEPROM_TC::getTempSeriesSize(), and EEPROM_TC::instance().
Referenced by PID_TC::PID_TC(), PYBIND11_MODULE(), and unittest().
key()
void key (char key)
Definition at line 79 of file libTC.cpp.
                    {
   Keypad_TC::instance()->_getPuppet()->push_back(key);
 }
References Keypad_TC::_getPuppet(), and Keypad_TC::instance().
Referenced by CalibrationManagement::handleKey(), ChangeGoogleSheetInterval::handleKey(), EnablePID::handleKey(), MainMenu::handleKey(), NumCollectorState::handleKey(), PHCalibration::handleKey(), PIDTuningMenu::handleKey(), ResetLCDScreen::handleKey(), SeeDeviceAddress::handleKey(), SeeDeviceUptime::handleKey(), SeePIDConstants::handleKey(), SeeTankID::handleKey(), SetChillOrHeat::handleKey(), TemperatureCalibration::handleKey(), TankControllerLib::handleUI(), and PYBIND11_MODULE().
lcd()
const char* lcd (int index)
Definition at line 83 of file libTC.cpp.
{
   std::vector<String> lines = LiquidCrystal_TC::instance()->getLines();
   String line = lines.at(index);
   int size = line.size();
   for (int i = 0; i < size; ++i) {
     if (line.at(i) < 32) {
       line.at(i) = '?';
     }
   }
   strncpy(lcdLine, line.c_str(), size);
   return lcdLine;
 }
References LiquidCrystal_TC::instance(), and lcdLine.
Referenced by PYBIND11_MODULE(), and unittest().
loop()
void loop ()
Definition at line 96 of file libTC.cpp.
             {
   TankControllerLib::instance()->loop();
 }
References TankControllerLib::instance(), and TankControllerLib::loop().
Referenced by PYBIND11_MODULE().
PYBIND11_MODULE()
PYBIND11_MODULE (libTC , m)
Definition at line 115 of file libTC.cpp.
{
   m.doc() = "pybind11 example plugin";  // optional module docstring
   m.def("dateTime", &dateTime, "TankController DateTime");
   m.def("eeprom", &eeprom, "TankController EEPROM");
   m.def("key", &key, "TankController key");
   m.def("lcd", &lcd, "TankController LiquidCrystal");
   m.def("loop", &loop, "TankController loop");
   m.def("serial", &serial, "TankController serial");
   m.def("setup", &setup, "TankController setup");
   m.def("version", &version, "TankController version");
 }
References dateTime(), eeprom(), key(), lcd(), loop(), serial(), setup(), and version().
serial()
string serial ()
Definition at line 100 of file libTC.cpp.
                 {
   GodmodeState *state = GODMODE();
   string result = string(state->serialPort[0].dataOut);
   state->serialPort[0].dataOut = "";
   return result;
 }
References state.
Referenced by PID_TC::logToSerial(), and PYBIND11_MODULE().
setup()
void setup ()
Definition at line 107 of file libTC.cpp.
              {
   TankControllerLib::instance()->setup();
 }
References TankControllerLib::instance(), and TankControllerLib::setup().
Referenced by PYBIND11_MODULE().
version()
const char* version ()
Definition at line 111 of file libTC.cpp.
                       {
   return TankControllerLib::instance()->version();
 }
References TankControllerLib::instance(), and TankControllerLib::version().
Referenced by EEPROM_TC::instance(), EEPROM_TC_3::isRightVersion(), and PYBIND11_MODULE().
Variable Documentation
lcdLine
char lcdLine[20]
Definition at line 20 of file libTC.cpp.
Referenced by lcd().