Tank Controller Lib: test/Menu.cpp File Reference
Menu.cpp File Reference
#include <Arduino.h>
#include <ArduinoUnitTests.h>
#include "Devices/Keypad_TC.h"
#include "TankControllerLib.h"
Functions
unittest (SetPHSetPoint)
unittest (SetTempSetPoint)
unittest (PHCalibration)
unittest (CalibrationManagement)
unittest (SetTankID)
unittest (SetGoogleSheetInterval)
unittest (SeeDeviceUptime)
unittest (SeeDeviceAddress)
unittest (ResetLCDScreen)
unittest (SeeTankID)
unittest (SeePIDConstants)
unittest (PIDTuningMenu)
unittest (TemperatureCalibration)
unittest (SetTime)
unittest (EnablePID)
unittest (SetChillOrHeat)
Function Documentation
unittest() [1/16]
unittest (CalibrationManagement)
Definition at line 54 of file Menu.cpp.
{
   TankControllerLib* tc = TankControllerLib::instance();
   LiquidCrystal_TC* lc = LiquidCrystal_TC::instance();
   Keypad* keypad = Keypad_TC::instance()->_getPuppet();
   std::vector<String> lines;
   tc->loop();
   keypad->push_back('D');
   tc->loop();  // recognize and apply the key entry
   assertEqual("Cal Management  ", lc->getLines().at(0));
   keypad->push_back('D');  // Don't finish (cancel)
   tc->loop();              // recognize and apply the key entry
   lines = lc->getLines();
   assertEqual("Main Menu       ", lc->getLines().at(0));
 }
References Keypad_TC::_getPuppet(), Keypad_TC::instance(), LiquidCrystal_TC::instance(), TankControllerLib::instance(), and TankControllerLib::loop().
unittest() [2/16]
unittest (EnablePID)
Definition at line 219 of file Menu.cpp.
                     {
   TankControllerLib* tc = TankControllerLib::instance();
   LiquidCrystal_TC* lc = LiquidCrystal_TC::instance();
   Keypad* keypad = Keypad_TC::instance()->_getPuppet();
   std::vector<String> lines;
   tc->loop();
   keypad->push_back('8');
   tc->loop();  // recognize and apply the key entry
   assertEqual("Enable PID?     ", lc->getLines().at(0));
   keypad->push_back('D');  // Don't finish (cancel)
   tc->loop();              // recognize and apply the key entry
   lines = lc->getLines();
   assertEqual("Main Menu       ", lc->getLines().at(0));
 }
References Keypad_TC::_getPuppet(), Keypad_TC::instance(), LiquidCrystal_TC::instance(), TankControllerLib::instance(), and TankControllerLib::loop().
unittest() [3/16]
unittest (PHCalibration)
Definition at line 39 of file Menu.cpp.
{
   TankControllerLib* tc = TankControllerLib::instance();
   LiquidCrystal_TC* lc = LiquidCrystal_TC::instance();
   Keypad* keypad = Keypad_TC::instance()->_getPuppet();
   std::vector<String> lines;
   tc->loop();
   keypad->push_back('C');
   tc->loop();  // recognize and apply the key entry
   assertEqual("pH-Calibration  ", lc->getLines().at(0));
   keypad->push_back('D');  // Don't finish (cancel)
   tc->loop();              // recognize and apply the key entry
   lines = lc->getLines();
   assertEqual("Main Menu       ", lc->getLines().at(0));
 }
References Keypad_TC::_getPuppet(), Keypad_TC::instance(), LiquidCrystal_TC::instance(), TankControllerLib::instance(), and TankControllerLib::loop().
unittest() [4/16]
unittest (PIDTuningMenu)
Definition at line 174 of file Menu.cpp.
{
   TankControllerLib* tc = TankControllerLib::instance();
   LiquidCrystal_TC* lc = LiquidCrystal_TC::instance();
   Keypad* keypad = Keypad_TC::instance()->_getPuppet();
   std::vector<String> lines;
   tc->loop();
   keypad->push_back('5');
   tc->loop();  // recognize and apply the key entry
   assertEqual("PID TUNING      ", lc->getLines().at(0));
   keypad->push_back('D');  // Don't finish (cancel)
   tc->loop();              // recognize and apply the key entry
   lines = lc->getLines();
   assertEqual("Main Menu       ", lc->getLines().at(0));
 }
References Keypad_TC::_getPuppet(), Keypad_TC::instance(), LiquidCrystal_TC::instance(), TankControllerLib::instance(), and TankControllerLib::loop().
unittest() [5/16]
unittest (ResetLCDScreen)
Definition at line 129 of file Menu.cpp.
{
   TankControllerLib* tc = TankControllerLib::instance();
   LiquidCrystal_TC* lc = LiquidCrystal_TC::instance();
   Keypad* keypad = Keypad_TC::instance()->_getPuppet();
   std::vector<String> lines;
   tc->loop();
   keypad->push_back('2');
   tc->loop();  // recognize and apply the key entry
   assertEqual("Clearing Screen ", lc->getLines().at(0));
   keypad->push_back('D');  // Don't finish (cancel)
   tc->loop();              // recognize and apply the key entry
   lines = lc->getLines();
   assertEqual("Main Menu       ", lc->getLines().at(0));
 }
References Keypad_TC::_getPuppet(), Keypad_TC::instance(), LiquidCrystal_TC::instance(), TankControllerLib::instance(), and TankControllerLib::loop().
unittest() [6/16]
unittest (SeeDeviceAddress)
Definition at line 114 of file Menu.cpp.
{
   TankControllerLib* tc = TankControllerLib::instance();
   LiquidCrystal_TC* lc = LiquidCrystal_TC::instance();
   Keypad* keypad = Keypad_TC::instance()->_getPuppet();
   std::vector<String> lines;
   tc->loop();
   keypad->push_back('1');
   tc->loop();  // recognize and apply the key entry
   assertEqual("Device address  ", lc->getLines().at(0));
   keypad->push_back('D');  // Don't finish (cancel)
   tc->loop();              // recognize and apply the key entry
   lines = lc->getLines();
   assertEqual("Main Menu       ", lc->getLines().at(0));
 }
References Keypad_TC::_getPuppet(), Keypad_TC::instance(), LiquidCrystal_TC::instance(), TankControllerLib::instance(), and TankControllerLib::loop().
unittest() [7/16]
unittest (SeeDeviceUptime)
Definition at line 99 of file Menu.cpp.
{
   TankControllerLib* tc = TankControllerLib::instance();
   LiquidCrystal_TC* lc = LiquidCrystal_TC::instance();
   Keypad* keypad = Keypad_TC::instance()->_getPuppet();
   std::vector<String> lines;
   tc->loop();
   keypad->push_back('0');
   tc->loop();  // recognize and apply the key entry
   assertEqual("Device time     ", lc->getLines().at(0));
   keypad->push_back('D');  // Don't finish (cancel)
   tc->loop();              // recognize and apply the key entry
   lines = lc->getLines();
   assertEqual("Main Menu       ", lc->getLines().at(0));
 }
References Keypad_TC::_getPuppet(), Keypad_TC::instance(), LiquidCrystal_TC::instance(), TankControllerLib::instance(), and TankControllerLib::loop().
unittest() [8/16]
unittest (SeePIDConstants)
Definition at line 159 of file Menu.cpp.
{
   TankControllerLib* tc = TankControllerLib::instance();
   LiquidCrystal_TC* lc = LiquidCrystal_TC::instance();
   Keypad* keypad = Keypad_TC::instance()->_getPuppet();
   std::vector<String> lines;
   tc->loop();
   keypad->push_back('4');
   tc->loop();  // recognize and apply the key entry
   assertEqual("PID Constants   ", lc->getLines().at(0));
   keypad->push_back('D');  // Don't finish (cancel)
   tc->loop();              // recognize and apply the key entry
   lines = lc->getLines();
   assertEqual("Main Menu       ", lc->getLines().at(0));
 }
References Keypad_TC::_getPuppet(), Keypad_TC::instance(), LiquidCrystal_TC::instance(), TankControllerLib::instance(), and TankControllerLib::loop().
unittest() [9/16]
unittest (SeeTankID)
Definition at line 144 of file Menu.cpp.
                     {
   TankControllerLib* tc = TankControllerLib::instance();
   LiquidCrystal_TC* lc = LiquidCrystal_TC::instance();
   Keypad* keypad = Keypad_TC::instance()->_getPuppet();
   std::vector<String> lines;
   tc->loop();
   keypad->push_back('3');
   tc->loop();  // recognize and apply the key entry
   assertEqual("Tank ID=        ", lc->getLines().at(0));
   keypad->push_back('D');  // Don't finish (cancel)
   tc->loop();              // recognize and apply the key entry
   lines = lc->getLines();
   assertEqual("Main Menu       ", lc->getLines().at(0));
 }
References Keypad_TC::_getPuppet(), Keypad_TC::instance(), LiquidCrystal_TC::instance(), TankControllerLib::instance(), and TankControllerLib::loop().
unittest() [10/16]
unittest (SetChillOrHeat)
Definition at line 234 of file Menu.cpp.
{
   TankControllerLib* tc = TankControllerLib::instance();
   LiquidCrystal_TC* lc = LiquidCrystal_TC::instance();
   Keypad* keypad = Keypad_TC::instance()->_getPuppet();
   std::vector<String> lines;
   tc->loop();
   keypad->push_back('9');
   tc->loop();  // recognize and apply the key entry
   assertEqual("1:Chill; 9:Heat ", lc->getLines().at(0));
   keypad->push_back('D');  // Don't finish (cancel)
   tc->loop();              // recognize and apply the key entry
   lines = lc->getLines();
   assertEqual("Main Menu       ", lc->getLines().at(0));
 }
References Keypad_TC::_getPuppet(), Keypad_TC::instance(), LiquidCrystal_TC::instance(), TankControllerLib::instance(), and TankControllerLib::loop().
unittest() [11/16]
unittest (SetGoogleSheetInterval)
Definition at line 84 of file Menu.cpp.
{
   TankControllerLib* tc = TankControllerLib::instance();
   LiquidCrystal_TC* lc = LiquidCrystal_TC::instance();
   Keypad* keypad = Keypad_TC::instance()->_getPuppet();
   std::vector<String> lines;
   tc->loop();
   keypad->push_back('*');
   tc->loop();  // recognize and apply the key entry
   assertEqual("G Sheet Minutes ", lc->getLines().at(0));
   keypad->push_back('D');  // Don't finish (cancel)
   tc->loop();              // recognize and apply the key entry
   lines = lc->getLines();
   assertEqual("Main Menu       ", lc->getLines().at(0));
 }
References Keypad_TC::_getPuppet(), Keypad_TC::instance(), LiquidCrystal_TC::instance(), TankControllerLib::instance(), and TankControllerLib::loop().
unittest() [12/16]
unittest (SetPHSetPoint)
Definition at line 7 of file Menu.cpp.
{
   TankControllerLib* tc = TankControllerLib::instance();
   LiquidCrystal_TC* lc = LiquidCrystal_TC::instance();
   Keypad* keypad = Keypad_TC::instance()->_getPuppet();
   std::vector<String> lines;
   tc->loop();
   lines = lc->getLines();
   assertEqual(" ONTHANK LAB", lc->getLines().at(0).substr(4));
   keypad->push_back('A');
   tc->loop();  // recognize and apply the key entry
   assertEqual("Set pH Set Point", lc->getLines().at(0));
   keypad->push_back('D');  // Don't finish (cancel)
   tc->loop();              // recognize and apply the key entry
   lines = lc->getLines();
   assertEqual("Main Menu       ", lc->getLines().at(0));
 }
References Keypad_TC::_getPuppet(), Keypad_TC::instance(), LiquidCrystal_TC::instance(), TankControllerLib::instance(), and TankControllerLib::loop().
unittest() [13/16]
unittest (SetTankID)
Definition at line 69 of file Menu.cpp.
                     {
   TankControllerLib* tc = TankControllerLib::instance();
   LiquidCrystal_TC* lc = LiquidCrystal_TC::instance();
   Keypad* keypad = Keypad_TC::instance()->_getPuppet();
   std::vector<String> lines;
   tc->loop();
   keypad->push_back('#');
   tc->loop();  // recognize and apply the key entry
   assertEqual("Set Tank ID#    ", lc->getLines().at(0));
   keypad->push_back('D');  // Don't finish (cancel)
   tc->loop();              // recognize and apply the key entry
   lines = lc->getLines();
   assertEqual("Main Menu       ", lc->getLines().at(0));
 }
References Keypad_TC::_getPuppet(), Keypad_TC::instance(), LiquidCrystal_TC::instance(), TankControllerLib::instance(), and TankControllerLib::loop().
unittest() [14/16]
unittest (SetTempSetPoint)
Definition at line 24 of file Menu.cpp.
{
   TankControllerLib* tc = TankControllerLib::instance();
   LiquidCrystal_TC* lc = LiquidCrystal_TC::instance();
   Keypad* keypad = Keypad_TC::instance()->_getPuppet();
   std::vector<String> lines;
   tc->loop();
   keypad->push_back('B');
   tc->loop();  // recognize and apply the key entry
   assertEqual("Set Temperature ", lc->getLines().at(0));
   keypad->push_back('D');  // Don't finish (cancel)
   tc->loop();              // recognize and apply the key entry
   lines = lc->getLines();
   assertEqual("Main Menu       ", lc->getLines().at(0));
 }
References Keypad_TC::_getPuppet(), Keypad_TC::instance(), LiquidCrystal_TC::instance(), TankControllerLib::instance(), and TankControllerLib::loop().
unittest() [15/16]
unittest (SetTime)
Definition at line 204 of file Menu.cpp.
                   {
   TankControllerLib* tc = TankControllerLib::instance();
   LiquidCrystal_TC* lc = LiquidCrystal_TC::instance();
   Keypad* keypad = Keypad_TC::instance()->_getPuppet();
   std::vector<String> lines;
   tc->loop();
   keypad->push_back('7');
   tc->loop();  // recognize and apply the key entry
   assertEqual("Set Year (YYYY):", lc->getLines().at(0));
   keypad->push_back('D');  // Don't finish (cancel)
   tc->loop();              // recognize and apply the key entry
   lines = lc->getLines();
   assertEqual("Main Menu       ", lc->getLines().at(0));
 }
References Keypad_TC::_getPuppet(), Keypad_TC::instance(), LiquidCrystal_TC::instance(), TankControllerLib::instance(), and TankControllerLib::loop().
unittest() [16/16]
unittest (TemperatureCalibration)
Definition at line 189 of file Menu.cpp.
{
   TankControllerLib* tc = TankControllerLib::instance();
   LiquidCrystal_TC* lc = LiquidCrystal_TC::instance();
   Keypad* keypad = Keypad_TC::instance()->_getPuppet();
   std::vector<String> lines;
   tc->loop();
   keypad->push_back('6');
   tc->loop();  // recognize and apply the key entry
   assertEqual("Temp Calibration", lc->getLines().at(0));
   keypad->push_back('D');  // Don't finish (cancel)
   tc->loop();              // recognize and apply the key entry
   lines = lc->getLines();
   assertEqual("Main Menu       ", lc->getLines().at(0));
 }
References Keypad_TC::_getPuppet(), Keypad_TC::instance(), LiquidCrystal_TC::instance(), TankControllerLib::instance(), and TankControllerLib::loop().