Tank Controller Lib: test/SD.cpp File Reference
SD.cpp File Reference
#include <Arduino.h>
#include <ArduinoUnitTests.h>
#include "SD_TC.h"
Functions
unittest_setup ()
unittest_teardown ()
unittest (singleton)
unittest (printRootDirectory)
Function Documentation
unittest() [1/2]
unittest (printRootDirectory)
Definition at line 21 of file SD.cpp.
{
   GodmodeState* state = GODMODE();
   SD.open("c", FILE_WRITE).close();
   SD.open("e", FILE_WRITE).close();
   SD.mkdir("d");
   SD.open("d/d1", FILE_WRITE).close();
   SD.open("d/d2", FILE_WRITE).close();
   SDClass_TC::instance()->printRootDirectory();
   String expect = String("c>>0\r\nd/\r\n>d1>>0\r\n>d2>>0\r\ne>>0\r\n");
   String output = String(state->serialPort[0].dataOut);
   std::replace(output.begin(), output.end(), '\t', '>');
   assertEqual(expect, output);
 }
References SDClass_TC::instance(), SDClass_TC::printRootDirectory(), and state.
unittest() [2/2]
unittest (singleton)
Definition at line 14 of file SD.cpp.
                     {
   SDClass_TC* thing1 = SDClass_TC::instance();
   SDClass_TC* thing2 = SDClass_TC::instance();
   assertTrue(thing1 != nullptr);
   assertEqual(thing1, thing2);
 }
References SDClass_TC::instance().
unittest_setup()
unittest_setup ()
Definition at line 6 of file SD.cpp.
                  {
   SD.removeAll();
 }
unittest_teardown()
unittest_teardown ()
Definition at line 10 of file SD.cpp.
                     {
   SD.removeAll();
 }