Tank Controller Lib: test/SetTankID.cpp File Reference
SetTankID.cpp File Reference
#include "SetTankID.h"
#include <Arduino.h>
#include <ArduinoUnitTests.h>
#include "EEPROM_TC.h"
#include "TankControllerLib.h"
Functions
void sleepHandler (int millis)
unittest (test)
Variables
std::vector< String > lines
Function Documentation
sleepHandler()
void sleepHandler (int millis)
Definition at line 11 of file SetTankID.cpp.
{
   lines = LiquidCrystal_TC::instance()->getLines();
 }
References LiquidCrystal_TC::instance(), and lines.
Referenced by unittest().
unittest()
unittest (test)
Definition at line 15 of file SetTankID.cpp.
                {
   TankControllerLibTest tc;
   SetTankID* test = new SetTankID(&tc);
   UIState::addSleepHandler(sleepHandler);
   tc.setNextState(test);
   // setValue
   test->setValue(12);
   UIState::removeSleepHandler(sleepHandler);
   assertEqual(12, EEPROM_TC::instance()->getTankID());
   // during the delay we showed the new value
   assertEqual("Tank ID = 12    ", lines[1]);
   assertTrue(tc.isOnMainMenu());
 }
References UIState::addSleepHandler(), EEPROM_TC::instance(), lines, UIState::removeSleepHandler(), and sleepHandler().
Variable Documentation
lines
std::vector<String> lines
Definition at line 9 of file SetTankID.cpp.
Referenced by sleepHandler(), and unittest().