Tank Controller Lib: test/SetChillOrHeat.cpp File Reference
SetChillOrHeat.cpp File Reference
#include "SetChillOrHeat.h"
#include <Arduino.h>
#include <ArduinoUnitTests.h>
#include "EEPROM_TC.h"
#include "TankControllerLib.h"
Functions
unittest (default)
unittest (ignoreInvalidValues)
unittest (switchToHeat)
unittest (switchToChill)
Function Documentation
unittest() [1/4]
unittest (default)
Definition at line 9 of file SetChillOrHeat.cpp.
                   {
   TankControllerLibTest tc;
   SetChillOrHeat* test = new SetChillOrHeat(&tc);
   tc.setNextState(test);
   assertTrue(EEPROM_TC::instance()->getHeat());
 }
References EEPROM_TC::instance().
unittest() [2/4]
unittest (ignoreInvalidValues)
Definition at line 16 of file SetChillOrHeat.cpp.
{
   TankControllerLibTest tc;
   SetChillOrHeat* test = new SetChillOrHeat(&tc);
   tc.setNextState(test);
   assertTrue(EEPROM_TC::instance()->getHeat());
   test->setValue(2.0);
   assertTrue(EEPROM_TC::instance()->getHeat());
   assertTrue(tc.isOnMainMenu());
 }
References EEPROM_TC::instance().
unittest() [3/4]
unittest (switchToChill)
Definition at line 36 of file SetChillOrHeat.cpp.
{
   TankControllerLibTest tc;
   SetChillOrHeat* test = new SetChillOrHeat(&tc);
   tc.setNextState(test);
   EEPROM_TC::instance()->setHeat(true);
   test->setValue(1.0);
   assertFalse(EEPROM_TC::instance()->getHeat());
   assertTrue(tc.isOnMainMenu());
 }
References EEPROM_TC::instance(), and EEPROM_TC::setHeat().
unittest() [4/4]
unittest (switchToHeat)
Definition at line 26 of file SetChillOrHeat.cpp.
{
   TankControllerLibTest tc;
   SetChillOrHeat* test = new SetChillOrHeat(&tc);
   tc.setNextState(test);
   EEPROM_TC::instance()->setHeat(false);
   test->setValue(9.0);
   assertTrue(EEPROM_TC::instance()->getHeat());
   assertTrue(tc.isOnMainMenu());
 }
References EEPROM_TC::instance(), and EEPROM_TC::setHeat().